version: "3.7"
services:
  app:
    image: backend
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
